spring:
  application:
    name: chat-server

---
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: secret
      database: admin

server:
  port: 8080